#!/bin/bash
# $0 Script
# $1 Path to downloaded file
# cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
echo "/*"
echo " * Code generator Copyright (C) 2022-2025 Dipl.-Inform. Kai Hofmann. All rights reserved!"
echo " */"
echo "package de.powerstat.validation.generated;"
echo ""
echo ""
echo "import java.util.Map;"
echo "import java.util.Locale;"
echo "import java.util.concurrent.ConcurrentHashMap;"
echo ""
echo ""
echo "/**"
echo " * International phone area codes."
echo " */"
echo "public final class GeneratedInternationalPhoneAreaCodes"
echo " {"
echo "  /**"
echo "   * Phone area codes map."
echo "   */"
echo "  private static final Map<String, String> PHONEAREAS = new ConcurrentHashMap<>();"
echo ""
echo ""
echo "  /**"
echo "   * Static initialization."
echo "   */"
echo "  static"
echo "   {"
for i in `grep -oE "^([A-Z]+),([0-9]+),([A-Z]+),([a-zA-Z]+),(Yes|No),([0-9]+),([0-9]+),([A-Z]+),([A-Z]+),([A-Z]{2})," $1`; do
  echo "    PHONEAREAS.put(\"$i\", \"\"); //\$NON-NLS-1\$"
done
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Private default constructor."
echo "   */"
echo "  private GeneratedInternationalPhoneAreaCodes()"
echo "   {"
echo "    super();"
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Check if phone area code exists."
echo "   *"
echo "   * @param phoneArea Phone area code to check"
echo "   * @return true if phone area code exists, false otherwise"
echo "   */"
echo "  public static boolean contains(final String phoneArea)"
echo "   {"
echo "    return PHONEAREAS.containsKey(phoneArea.toUpperCase(Locale.getDefault()));"
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Get english country name for phone area code."
echo "   *"
echo "   * @param phoneArea Phone area code"
echo "   * @return Country name in english"
echo "   */"
echo "  public static String getName(final String phoneArea)"
echo "   {"
echo "    return PHONEAREAS.get(phoneArea.toUpperCase(Locale.getDefault()));"
echo "   }"
echo ""
echo ""
echo "}"
