#!/bin/bash
# $0 Script
# $1 Path to downloaded file
# cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
echo "package de.powerstat.validation.generated;"
echo ""
echo ""
echo "import java.util.ArrayList;"
echo "import java.util.List;"
echo "import java.util.Locale;"
echo ""
echo ""
echo "public final class GeneratedISO3166A2"
echo " {"
echo "  private static final List<String> ALPHA2 = new ArrayList<>();"
echo ""
echo ""
echo "  static"
echo "   {"
for i in `grep -oE "[A-Z]{2}" $1`; do
  echo "    ALPHA2.add(\"$i\".toUpperCase(Locale.getDefault()));"
done
echo "   }"
echo ""
echo ""
echo "  private GeneratedISO3166A2()"
echo "   {"
echo "    super();"
echo "   }"
echo ""
echo ""
echo "  public static boolean contains(String alpha2)"
echo "   {"
echo "    return ALPHA2.contains(alpha2.toUpperCase(Locale.getDefault()));"
echo "   }"
echo ""
echo ""
echo "}"
