#!/bin/bash
# $0 Script
# $1 Path to downloaded file
# cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
echo "/*"
echo " * Code generator Copyright (C) 2025 Dipl.-Inform. Kai Hofmann. All rights reserved!"
echo " */"
echo "package de.powerstat.validation.generated;"
echo ""
echo ""
echo "import java.util.HashSet;"
echo "import java.util.Set;"
echo "import java.util.Locale;"
echo ""
echo ""
echo "/**"
echo " * URI scheme names."
echo " */"
echo "public final class GeneratedURISchemeNames"
echo " {"
echo "  /**"
echo "   * URI scheme name list."
echo "   */"
echo "  private static final Set<String> URISCHEMES = new HashSet<>();"
echo ""
echo ""
echo "  /**"
echo "   * Static initialization."
echo "   */"
echo "  static"
echo "   {"
for i in `grep -oE "^([a-z][a-z0-9+-]+)" $1`; do
  echo "    URISCHEMES.add(\"$i\"); //\$NON-NLS-1\$"
done
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Private default constructor."
echo "   */"
echo "  private GeneratedURISchemeNames()"
echo "   {"
echo "    super();"
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Check if uri scheme name exists."
echo "   *"
echo "   * @param scheme URI scheme name"
echo "   * @return true if uri scheme name exists, false otherwise"
echo "   */"
echo "  public static boolean contains(final String scheme)"
echo "   {"
echo "    return URISCHEMES.contains(scheme.toLowerCase(Locale.getDefault()));"
echo "   }"
echo ""
echo "}"
