#!/bin/bash
# $0 Script
# $1 Path to downloaded file
# cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
echo "/*"
echo " * Code generator Copyright (C) 2022-2025 Dipl.-Inform. Kai Hofmann. All rights reserved!"
echo " */"
echo "package de.powerstat.ddd.generated;"
echo ""
echo ""
echo "import java.util.Map;"
echo "import java.util.Locale;"
echo "import java.util.concurrent.ConcurrentHashMap;"
echo ""
echo "import de.powerstat.ddd.values.geo.Country;"
echo ""
echo ""
echo "/**"
echo " * International phone area codes."
echo " */"
echo "public final class GeneratedInternationalPhoneAreaCodes"
echo " {"
echo "  /**"
echo "   * Phone area codes map."
echo "   */"
echo "  private static final Map<String, Country> PHONEAREAS = new ConcurrentHashMap<>();"
echo ""
echo ""
echo "  /**"
echo "   * Static initialization."
echo "   */"
echo "  static"
echo "   {"
awk -F, '{if ((NR > 1) && (index($2, "\"") == 0)) {print "    PHONEAREAS.put(\""$2"\", Country.of(\""$10"\")); //\$NON-NLS-1\$"}}' $1
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Private default constructor."
echo "   */"
echo "  private GeneratedInternationalPhoneAreaCodes()"
echo "   {"
echo "    super();"
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Check if phone area code exists."
echo "   *"
echo "   * @param phoneArea Phone area code to check"
echo "   * @return true if phone area code exists, false otherwise"
echo "   */"
echo "  public static boolean contains(final String phoneArea)"
echo "   {"
echo "    return PHONEAREAS.containsKey(phoneArea.toUpperCase(Locale.getDefault()));"
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Get country for phone area code."
echo "   *"
echo "   * @param phoneArea Phone area code"
echo "   * @return Country"
echo "   */"
echo "  public static Country getCountry(final String phoneArea)"
echo "   {"
echo "    return PHONEAREAS.get(phoneArea.toUpperCase(Locale.getDefault()));"
echo "   }"
echo ""
echo ""
echo "  /**"
echo "   * Get phone area code for country."
echo "   *"
echo "   * @param country Country"
echo "   * @return Phone area code or empty string"
echo "   */"
echo "  public static String getForCountry(final Country country)"
echo "   {"
echo "    for (Map.Entry<String, Country> entry : PHONEAREAS.entrySet())"
echo "     {"
echo "      if (country.equals(entry.getValue()))"
echo "       {"
echo "        return entry.getKey();"
echo "       }"
echo "     }"
echo "    return \"\";"
echo "   }"
echo ""
echo "}"
